/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugas2ap2;

import javax.swing.JFrame;

/**
 *
 * @author MasterPro
 */
public class frmUtama extends javax.swing.JFrame {

    /**
     * Creates new form frmUtama
     */
    public frmUtama() {
        initComponents();
        setTitle("Point Of Sales System - 11140360");
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mnFile = new javax.swing.JMenu();
        mnLogin = new javax.swing.JMenuItem();
        mnLogout = new javax.swing.JMenuItem();
        mnKeluar = new javax.swing.JMenuItem();
        mnED = new javax.swing.JMenu();
        mnKat = new javax.swing.JMenuItem();
        mnPlg = new javax.swing.JMenuItem();
        mnSpl = new javax.swing.JMenuItem();
        mnBrg = new javax.swing.JMenuItem();
        mnRek = new javax.swing.JMenuItem();
        mnAk = new javax.swing.JMenuItem();
        mnTrans = new javax.swing.JMenu();
        mnPgb = new javax.swing.JMenuItem();
        mnPjb = new javax.swing.JMenuItem();
        mnLap = new javax.swing.JMenu();
        mnTnt = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnFile.setText("File");

        mnLogin.setText("Login");
        mnFile.add(mnLogin);

        mnLogout.setText("Log out");
        mnFile.add(mnLogout);

        mnKeluar.setText("Keluar");
        mnFile.add(mnKeluar);

        jMenuBar1.add(mnFile);

        mnED.setText("Entri Data");

        mnKat.setText("Kategori");
        mnED.add(mnKat);

        mnPlg.setText("Pelanggan");
        mnPlg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnPlgActionPerformed(evt);
            }
        });
        mnED.add(mnPlg);

        mnSpl.setText("Supplier");
        mnSpl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSplActionPerformed(evt);
            }
        });
        mnED.add(mnSpl);

        mnBrg.setText("Barang");
        mnBrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnBrgActionPerformed(evt);
            }
        });
        mnED.add(mnBrg);

        mnRek.setText("Rekening");
        mnED.add(mnRek);

        mnAk.setText("Akun");
        mnAk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAkActionPerformed(evt);
            }
        });
        mnED.add(mnAk);

        jMenuBar1.add(mnED);

        mnTrans.setText("Transaksi");

        mnPgb.setText("Pengadaan Barang");
        mnTrans.add(mnPgb);

        mnPjb.setText("Penjualan Barang");
        mnTrans.add(mnPjb);

        jMenuBar1.add(mnTrans);

        mnLap.setText("Laporan");
        jMenuBar1.add(mnLap);

        mnTnt.setText("Tentang");
        jMenuBar1.add(mnTnt);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnBrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnBrgActionPerformed
        
    }//GEN-LAST:event_mnBrgActionPerformed

    private void mnPlgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnPlgActionPerformed
       
        ;
    }//GEN-LAST:event_mnPlgActionPerformed

    private void mnSplActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSplActionPerformed
        
    }//GEN-LAST:event_mnSplActionPerformed

    private void mnAkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAkActionPerformed
        new frmAkun(this, true).setVisible(true);
    }//GEN-LAST:event_mnAkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnAk;
    private javax.swing.JMenuItem mnBrg;
    private javax.swing.JMenu mnED;
    private javax.swing.JMenu mnFile;
    private javax.swing.JMenuItem mnKat;
    private javax.swing.JMenuItem mnKeluar;
    private javax.swing.JMenu mnLap;
    private javax.swing.JMenuItem mnLogin;
    private javax.swing.JMenuItem mnLogout;
    private javax.swing.JMenuItem mnPgb;
    private javax.swing.JMenuItem mnPjb;
    private javax.swing.JMenuItem mnPlg;
    private javax.swing.JMenuItem mnRek;
    private javax.swing.JMenuItem mnSpl;
    private javax.swing.JMenu mnTnt;
    private javax.swing.JMenu mnTrans;
    // End of variables declaration//GEN-END:variables
}
